# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getWithin <- function(alpha_, X_) {
    .Call(`_cptest1_getWithin`, alpha_, X_)
}

getBetween <- function(alpha_, X_, Y_) {
    .Call(`_cptest1_getBetween`, alpha_, X_, Y_)
}

split_re <- function(s_, e_, D_, min_size_) {
    .Call(`_cptest1_split_re`, s_, e_, D_, min_size_)
}

split_re1 <- function(s_, e_, D_, min_size_) {
    .Call(`_cptest1_split_re1`, s_, e_, D_, min_size_)
}

